/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as OrganizacaoEditarRouteImport } from './routes/organizacao.editar'
import { Route as OrganizacoesIndexRouteImport } from './routes/organizacoes.index'
import { Route as OrganizacoesSlugRouteImport } from './routes/organizacoes.$slug'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAdminRouteImport } from './routes/painel.admin'
import { Route as PainelOrganizacaoRouteImport } from './routes/painel.organizacao'
import { Route as PainelVoluntarioRouteImport } from './routes/painel.voluntario'
import { Route as PerfilEditarRouteImport } from './routes/perfil.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacaoEditarRoute = OrganizacaoEditarRouteImport.update({
  id: '/organizacao/editar',
  path: '/organizacao/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesIndexRoute = OrganizacoesIndexRouteImport.update({
  id: '/organizacoes/',
  path: '/organizacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesSlugRoute = OrganizacoesSlugRouteImport.update({
  id: '/organizacoes/$slug',
  path: '/organizacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/painel/admin',
  path: '/painel/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelOrganizacaoRoute = PainelOrganizacaoRouteImport.update({
  id: '/painel/organizacao',
  path: '/painel/organizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelVoluntarioRoute = PainelVoluntarioRouteImport.update({
  id: '/painel/voluntario',
  path: '/painel/voluntario',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilEditarRoute = PerfilEditarRouteImport.update({
  id: '/perfil/editar',
  path: '/perfil/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/organizacao/editar': typeof OrganizacaoEditarRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/organizacao': typeof PainelOrganizacaoRoute
  '/painel/voluntario': typeof PainelVoluntarioRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/organizacao/editar': typeof OrganizacaoEditarRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/organizacao': typeof PainelOrganizacaoRoute
  '/painel/voluntario': typeof PainelVoluntarioRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/organizacoes': typeof OrganizacoesIndexRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/organizacao/editar': typeof OrganizacaoEditarRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/organizacao': typeof PainelOrganizacaoRoute
  '/painel/voluntario': typeof PainelVoluntarioRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/quem-somos'
    | '/organizacao/editar'
    | '/organizacoes/$slug'
    | '/painel/admin'
    | '/painel/organizacao'
    | '/painel/voluntario'
    | '/perfil/editar'
    | '/organizacoes/'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/quem-somos'
    | '/organizacao/editar'
    | '/organizacoes/$slug'
    | '/painel/admin'
    | '/painel/organizacao'
    | '/painel/voluntario'
    | '/perfil/editar'
    | '/organizacoes'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/quem-somos'
    | '/organizacao/editar'
    | '/organizacoes/$slug'
    | '/painel/admin'
    | '/painel/organizacao'
    | '/painel/voluntario'
    | '/perfil/editar'
    | '/organizacoes/'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ImpactoRoute: typeof ImpactoRoute
  OportunidadesRoute: typeof OportunidadesRoute
  QuemSomosRoute: typeof QuemSomosRoute
  OrganizacaoEditarRoute: typeof OrganizacaoEditarRoute
  OrganizacoesSlugRoute: typeof OrganizacoesSlugRoute
  PainelAdminRoute: typeof PainelAdminRoute
  PainelOrganizacaoRoute: typeof PainelOrganizacaoRoute
  PainelVoluntarioRoute: typeof PainelVoluntarioRoute
  PerfilEditarRoute: typeof PerfilEditarRoute
  OrganizacoesIndexRoute: typeof OrganizacoesIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacao/editar': {
      id: '/organizacao/editar'
      path: '/organizacao/editar'
      fullPath: '/organizacao/editar'
      preLoaderRoute: typeof OrganizacaoEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/': {
      id: '/organizacoes/'
      path: '/organizacoes'
      fullPath: '/organizacoes/'
      preLoaderRoute: typeof OrganizacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$slug': {
      id: '/organizacoes/$slug'
      path: '/organizacoes/$slug'
      fullPath: '/organizacoes/$slug'
      preLoaderRoute: typeof OrganizacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/admin': {
      id: '/painel/admin'
      path: '/painel/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/organizacao': {
      id: '/painel/organizacao'
      path: '/painel/organizacao'
      fullPath: '/painel/organizacao'
      preLoaderRoute: typeof PainelOrganizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/voluntario': {
      id: '/painel/voluntario'
      path: '/painel/voluntario'
      fullPath: '/painel/voluntario'
      preLoaderRoute: typeof PainelVoluntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/editar': {
      id: '/perfil/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof PerfilEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ImpactoRoute: ImpactoRoute,
  OportunidadesRoute: OportunidadesRoute,
  QuemSomosRoute: QuemSomosRoute,
  OrganizacaoEditarRoute: OrganizacaoEditarRoute,
  OrganizacoesSlugRoute: OrganizacoesSlugRoute,
  PainelAdminRoute: PainelAdminRoute,
  PainelOrganizacaoRoute: PainelOrganizacaoRoute,
  PainelVoluntarioRoute: PainelVoluntarioRoute,
  PerfilEditarRoute: PerfilEditarRoute,
  OrganizacoesIndexRoute: OrganizacoesIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
