/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as OrganizacoesIndexRouteImport } from './routes/organizacoes.index'
import { Route as OrganizacoesSlugRouteImport } from './routes/organizacoes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesIndexRoute = OrganizacoesIndexRouteImport.update({
  id: '/organizacoes/',
  path: '/organizacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesSlugRoute = OrganizacoesSlugRouteImport.update({
  id: '/organizacoes/$slug',
  path: '/organizacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/organizacoes': typeof OrganizacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/impacto': typeof ImpactoRoute
  '/oportunidades': typeof OportunidadesRoute
  '/organizacoes/$slug': typeof OrganizacoesSlugRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/organizacoes/$slug'
    | '/organizacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/organizacoes/$slug'
    | '/organizacoes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/impacto'
    | '/oportunidades'
    | '/organizacoes/$slug'
    | '/organizacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ImpactoRoute: typeof ImpactoRoute
  OportunidadesRoute: typeof OportunidadesRoute
  OrganizacoesSlugRoute: typeof OrganizacoesSlugRoute
  OrganizacoesIndexRoute: typeof OrganizacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/': {
      id: '/organizacoes/'
      path: '/organizacoes'
      fullPath: '/organizacoes/'
      preLoaderRoute: typeof OrganizacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$slug': {
      id: '/organizacoes/$slug'
      path: '/organizacoes/$slug'
      fullPath: '/organizacoes/$slug'
      preLoaderRoute: typeof OrganizacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ImpactoRoute: ImpactoRoute,
  OportunidadesRoute: OportunidadesRoute,
  OrganizacoesSlugRoute: OrganizacoesSlugRoute,
  OrganizacoesIndexRoute: OrganizacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
